### ISSUE TITLE
No way to specify unknown device

### ISSUE THREAD

**Issue by alchemyst** [jckantor/TCLab#47]
After #46 there is no way to connect to a device which works but is not in `tclab.arduinos`.

Technically, it is possible to `import tclab`, then update `tclab.arduinos`, then connect, but this is not obvious from the user side.

**Comment by jckantor** [comment]
That was a deliberate decision, but I get your point.  There are all kinds of Arduino Uno clones out there.  So I changed this to return the name of the device if known, otherwise use the vendor ID/product ID string as the name of the device. Now, so long as the firmware can be loaded the code ought to connect.
